# -*- coding: utf-8 -*-
"""MarioBros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgZzN21nWe_YY5BZzvB71dzxlDjX4cbu

# 🎮 MINI JEU MARIO BROS 🎮

---

** Réalisé par :** ANTON NELCON Steve  
** Projet :** Personnel

<h1 style="background-color:#FFD700; color:black; padding:10px; border-radius:8px;">
→ Analyse de la Datasheet
</h1>

## **→Affichage de toute les datasheet**
"""

import pandas as pd
from tabulate import tabulate

# Charger le dataset
df = pd.read_csv("mario_dataset.csv")

# Fonction pour afficher un titre
def afficher_section(titre):
    print("\n" + "="*len(titre))
    print(titre)
    print("="*len(titre))

# 1️⃣ Aperçu des 5 premières lignes
afficher_section("Aperçu des 5 premières lignes")
print(tabulate(df.head(), headers='keys', tablefmt='fancy_grid', showindex=False))

# 2️⃣ Aperçu des 5 dernières lignes
afficher_section("Aperçu des 5 dernières lignes")
print(tabulate(df.tail(), headers='keys', tablefmt='fancy_grid', showindex=False))

# 3️⃣ Informations générales
afficher_section("Infos du DataFrame")
print(df.info())

# 4️⃣ Colonnes du dataset
afficher_section("Colonnes du dataset")
for col in df.columns:
    print(f"- {col}")

# 5️⃣ Statistiques descriptives
afficher_section("Statistiques descriptives")
print(tabulate(df.describe(), headers='keys', tablefmt='fancy_grid'))

# 6️⃣ Vérifier les valeurs manquantes
afficher_section("Valeurs manquantes par colonne")
print(tabulate(df.isnull().sum().reset_index().rename(columns={'index':'Colonne', 0:'Valeurs manquantes'}),
               headers='keys', tablefmt='fancy_grid', showindex=False))

# 7️⃣ Taille du DataFrame
afficher_section("Taille du DataFrame")
print(f"Nombre de lignes : {df.shape[0]}")
print(f"Nombre de colonnes : {df.shape[1]}")

# 8️⃣ Afficher toutes les lignes si dataset petit
# pd.set_option('display.max_rows', None)
# print(tabulate(df, headers='keys', tablefmt='fancy_grid', showindex=False))

"""## **→ Affichage des colonnes**"""

import pandas as pd
from tabulate import tabulate

# Charger le dataset
df = pd.read_csv("mario_dataset.csv")

# Préparer les colonnes pour le tableau
colonnes_table = [[idx + 1, col] for idx, col in enumerate(df.columns)]

# Afficher le tableau
print(tabulate(colonnes_table, headers=["N°", "Nom de la colonne"], tablefmt="fancy_grid"))

"""## **→Affichage des 10 premières lignes avec colonnes**"""

import pandas as pd
from tabulate import tabulate

# Charger le dataset
df = pd.read_csv("mario_dataset.csv")

# Prendre les 10 premières lignes
df_10 = df.head(10)

# Afficher sous forme de tableau
print(tabulate(df_10, headers='keys', tablefmt='fancy_grid', showindex=True))

"""## **→Afficher tout les personnages**"""

import pandas as pd
from tabulate import tabulate

# Charger le dataset
df = pd.read_csv("mario_dataset.csv")

# Vérifier si la colonne 'player_id' existe
if 'player_id' in df.columns:
    # Extraire la colonne
    player_ids = df['player_id']

    # Préparer le tableau
    tableau = [[idx + 1, pid] for idx, pid in enumerate(player_ids)]

    # Afficher sous forme de tableau
    print(tabulate(tableau, headers=["N°", "player_id"], tablefmt="fancy_grid"))
else:
    print("La colonne 'player_id' n'existe pas dans le dataset. Voici les colonnes disponibles :")
    print(df.columns.tolist())

"""## **→Afficher tout les niveaux du jeu**"""

import pandas as pd
from tabulate import tabulate

# Charger le dataset
df = pd.read_csv("mario_dataset.csv")

# Vérifier si la colonne 'level' existe
if 'player_id' in df.columns:
    # Extraire la colonne
    player_ids = df['level']

    # Préparer le tableau
    tableau = [[idx + 1, pid] for idx, pid in enumerate(player_ids)]

    # Afficher sous forme de tableau
    print(tabulate(tableau, headers=[ "level"], tablefmt="fancy_grid"))
else:
    print("La colonne 'player_id' n'existe pas dans le dataset. Voici les colonnes disponibles :")
    print(df.columns.tolist())

"""**→ Le Combat de l'univers de Mario**"""

import pandas as pd
from tabulate import tabulate
import random

# Charger le dataset
df = pd.read_csv("mario_dataset.csv")

# Vérifier les colonnes
print("Colonnes disponibles :")
print(df.columns.tolist())

col_personnages = 'player_id'  # Colonne des personnages

# Sélectionner 10 personnages aléatoires
df_10 = df.sample(n=10, random_state=42).reset_index(drop=True)

# Afficher les 10 personnages jouables
def afficher_personnages():
    tableau = [[idx + 1, pers] for idx, pers in enumerate(df_10[col_personnages])]
    print(tabulate(tableau, headers=["N°", "Personnage"], tablefmt="fancy_grid"))

# Choix d'un personnage
def choisir_personnage():
    afficher_personnages()
    while True:
        try:
            choix = int(input("Choisis le numéro d'un personnage (1-10) : "))
            if 1 <= choix <= 10:
                personnage = df_10.iloc[choix-1]
                return personnage
            else:
                print("⚠️ Veuillez choisir un numéro entre 1 et 10.")
        except ValueError:
            print("⚠️ Entrée invalide. Veuillez entrer un numéro.")

# Combat aléatoire entre deux personnages
def combat(p1, p2):
    gagnant = random.choice([p1[col_personnages], p2[col_personnages]])
    print(f"\nCombat entre {p1[col_personnages]} et {p2[col_personnages]} :")
    print(f"🏆 Le gagnant est {gagnant} !")

# Jeu principal
print("Bienvenue dans le jeu de combat Mario !\n")
personnage1 = choisir_personnage()
personnage2 = choisir_personnage()
combat(personnage1, personnage2)